# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formLogin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(651, 352)
        Dialog.setModal(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 611, 291))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 49, 401, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtPasswd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswd.setObjectName("txtPasswd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPasswd)
        self.txtEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtEmail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.btnLogin = QtWidgets.QPushButton(self.tab_3)
        self.btnLogin.setGeometry(QtCore.QRect(70, 129, 89, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(self.tab_3)
        self.btnExit.setGeometry(QtCore.QRect(180, 129, 89, 31))
        self.btnExit.setObjectName("btnExit")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(130, 19, 151, 17))
        self.label_3.setObjectName("label_3")
        self.btnEsqueciSenha = QtWidgets.QPushButton(self.tab_3)
        self.btnEsqueciSenha.setGeometry(QtCore.QRect(83, 179, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnEsqueciSenha.setFont(font)
        self.btnEsqueciSenha.setObjectName("btnEsqueciSenha")
        self.checkBoxSalvarLogin = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxSalvarLogin.setGeometry(QtCore.QRect(310, 130, 161, 23))
        self.checkBoxSalvarLogin.setObjectName("checkBoxSalvarLogin")
        self.checkBoxLoginAutomatico = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxLoginAutomatico.setGeometry(QtCore.QRect(310, 160, 201, 23))
        self.checkBoxLoginAutomatico.setObjectName("checkBoxLoginAutomatico")
        self.checkBoxLoginAutoStart = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxLoginAutoStart.setGeometry(QtCore.QRect(310, 190, 241, 23))
        self.checkBoxLoginAutoStart.setObjectName("checkBoxLoginAutoStart")
        self.checkBoxAtalhoDesktop = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxAtalhoDesktop.setGeometry(QtCore.QRect(310, 220, 261, 23))
        self.checkBoxAtalhoDesktop.setObjectName("checkBoxAtalhoDesktop")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 421, 151))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtEmail_minhaConta = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtEmail_minhaConta.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtEmail_minhaConta.setObjectName("txtEmail_minhaConta")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtEmail_minhaConta)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtPasswd_minhaConta = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPasswd_minhaConta.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswd_minhaConta.setObjectName("txtPasswd_minhaConta")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPasswd_minhaConta)
        self.txtNovaSenha = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtNovaSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNovaSenha.setObjectName("txtNovaSenha")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtNovaSenha)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtNovaSenha2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtNovaSenha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNovaSenha2.setObjectName("txtNovaSenha2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtNovaSenha2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.btnAlterarSenha = QtWidgets.QPushButton(self.tab_4)
        self.btnAlterarSenha.setGeometry(QtCore.QRect(180, 160, 89, 31))
        self.btnAlterarSenha.setObjectName("btnAlterarSenha")
        self.tabWidget.addTab(self.tab_4, "")
        self.lblStatus = QtWidgets.QLabel(Dialog)
        self.lblStatus.setGeometry(QtCore.QRect(0, 300, 611, 31))
        self.lblStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.txtEmail)
        Dialog.setTabOrder(self.txtEmail, self.txtPasswd)
        Dialog.setTabOrder(self.txtPasswd, self.btnLogin)
        Dialog.setTabOrder(self.btnLogin, self.btnExit)
        Dialog.setTabOrder(self.btnExit, self.checkBoxSalvarLogin)
        Dialog.setTabOrder(self.checkBoxSalvarLogin, self.checkBoxLoginAutomatico)
        Dialog.setTabOrder(self.checkBoxLoginAutomatico, self.checkBoxLoginAutoStart)
        Dialog.setTabOrder(self.checkBoxLoginAutoStart, self.checkBoxAtalhoDesktop)
        Dialog.setTabOrder(self.checkBoxAtalhoDesktop, self.btnEsqueciSenha)
        Dialog.setTabOrder(self.btnEsqueciSenha, self.txtEmail_minhaConta)
        Dialog.setTabOrder(self.txtEmail_minhaConta, self.txtPasswd_minhaConta)
        Dialog.setTabOrder(self.txtPasswd_minhaConta, self.txtNovaSenha)
        Dialog.setTabOrder(self.txtNovaSenha, self.txtNovaSenha2)
        Dialog.setTabOrder(self.txtNovaSenha2, self.btnAlterarSenha)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Email:"))
        self.label_2.setText(_translate("Dialog", "Senha:"))
        self.btnLogin.setText(_translate("Dialog", "Entrar"))
        self.btnExit.setText(_translate("Dialog", "Cancelar"))
        self.label_3.setText(_translate("Dialog", "Portão Virtual - Login"))
        self.btnEsqueciSenha.setText(_translate("Dialog", "Esqueci minha senha"))
        self.checkBoxSalvarLogin.setText(_translate("Dialog", "Salvar login"))
        self.checkBoxLoginAutomatico.setText(_translate("Dialog", "Login automático"))
        self.checkBoxLoginAutoStart.setText(_translate("Dialog", "Iniciar junto com o Windows"))
        self.checkBoxAtalhoDesktop.setText(_translate("Dialog", "Criar atalho na Área de Trabalho"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "Email:"))
        self.label_6.setText(_translate("Dialog", "Senha atual:"))
        self.label_5.setText(_translate("Dialog", "Repetir nova senha:"))
        self.label_7.setText(_translate("Dialog", "Nova senha:"))
        self.btnAlterarSenha.setText(_translate("Dialog", "Alterar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Alterar Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

