# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formLogin.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formLogin(object):
    def setupUi(self, formLogin):
        formLogin.setObjectName("formLogin")
        formLogin.setWindowModality(QtCore.Qt.WindowModal)
        formLogin.resize(594, 307)
        formLogin.setFocusPolicy(QtCore.Qt.NoFocus)
        formLogin.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        formLogin.setAcceptDrops(False)
        formLogin.setLayoutDirection(QtCore.Qt.LeftToRight)
        formLogin.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.lblStatus = QtWidgets.QLabel(formLogin)
        self.lblStatus.setGeometry(QtCore.QRect(0, 270, 581, 31))
        self.lblStatus.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lblStatus.setText("")
        self.lblStatus.setObjectName("lblStatus")
        self.tabWidget = QtWidgets.QTabWidget(formLogin)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 581, 251))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 49, 401, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txtPasswd = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtPasswd.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswd.setObjectName("txtPasswd")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPasswd)
        self.txtEmail = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtEmail.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtEmail)
        self.btnLogin = QtWidgets.QPushButton(self.tab_3)
        self.btnLogin.setGeometry(QtCore.QRect(70, 129, 89, 31))
        self.btnLogin.setObjectName("btnLogin")
        self.btnExit = QtWidgets.QPushButton(self.tab_3)
        self.btnExit.setGeometry(QtCore.QRect(180, 129, 89, 31))
        self.btnExit.setObjectName("btnExit")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(130, 19, 151, 17))
        self.label_3.setObjectName("label_3")
        self.btnEsqueciSenha = QtWidgets.QPushButton(self.tab_3)
        self.btnEsqueciSenha.setGeometry(QtCore.QRect(100, 179, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btnEsqueciSenha.setFont(font)
        self.btnEsqueciSenha.setObjectName("btnEsqueciSenha")
        self.checkBoxSalvarLogin = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxSalvarLogin.setGeometry(QtCore.QRect(320, 130, 111, 23))
        self.checkBoxSalvarLogin.setObjectName("checkBoxSalvarLogin")
        self.checkBoxLoginAutomatico = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxLoginAutomatico.setGeometry(QtCore.QRect(320, 160, 151, 23))
        self.checkBoxLoginAutomatico.setObjectName("checkBoxLoginAutomatico")
        self.checkBoxLoginAutoStart = QtWidgets.QCheckBox(self.tab_3)
        self.checkBoxLoginAutoStart.setGeometry(QtCore.QRect(320, 190, 221, 23))
        self.checkBoxLoginAutoStart.setObjectName("checkBoxLoginAutoStart")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 10, 421, 151))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txtEmail_minhaConta = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtEmail_minhaConta.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtEmail_minhaConta.setObjectName("txtEmail_minhaConta")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtEmail_minhaConta)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.txtPasswd_minhaConta = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtPasswd_minhaConta.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPasswd_minhaConta.setObjectName("txtPasswd_minhaConta")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPasswd_minhaConta)
        self.txtNovaSenha = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtNovaSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNovaSenha.setObjectName("txtNovaSenha")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txtNovaSenha)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.txtNovaSenha2 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.txtNovaSenha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtNovaSenha2.setObjectName("txtNovaSenha2")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtNovaSenha2)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.btnAlterarSenha = QtWidgets.QPushButton(self.tab_4)
        self.btnAlterarSenha.setGeometry(QtCore.QRect(180, 160, 89, 31))
        self.btnAlterarSenha.setObjectName("btnAlterarSenha")
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(formLogin)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(formLogin)
        formLogin.setTabOrder(self.txtEmail, self.txtPasswd)
        formLogin.setTabOrder(self.txtPasswd, self.btnLogin)
        formLogin.setTabOrder(self.btnLogin, self.btnExit)
        formLogin.setTabOrder(self.btnExit, self.btnEsqueciSenha)
        formLogin.setTabOrder(self.btnEsqueciSenha, self.txtEmail_minhaConta)
        formLogin.setTabOrder(self.txtEmail_minhaConta, self.txtPasswd_minhaConta)
        formLogin.setTabOrder(self.txtPasswd_minhaConta, self.txtNovaSenha)
        formLogin.setTabOrder(self.txtNovaSenha, self.txtNovaSenha2)
        formLogin.setTabOrder(self.txtNovaSenha2, self.btnAlterarSenha)
        formLogin.setTabOrder(self.btnAlterarSenha, self.tabWidget)

    def retranslateUi(self, formLogin):
        _translate = QtCore.QCoreApplication.translate
        formLogin.setWindowTitle(_translate("formLogin", "Login - Portão Virtual"))
        self.label.setText(_translate("formLogin", "Email:"))
        self.label_2.setText(_translate("formLogin", "Senha:"))
        self.btnLogin.setText(_translate("formLogin", "Entrar"))
        self.btnExit.setText(_translate("formLogin", "Cancelar"))
        self.label_3.setText(_translate("formLogin", "Portão Virtual - Login"))
        self.btnEsqueciSenha.setText(_translate("formLogin", "Esqueci minha senha"))
        self.checkBoxSalvarLogin.setText(_translate("formLogin", "Salvar login"))
        self.checkBoxLoginAutomatico.setText(_translate("formLogin", "Login automático"))
        self.checkBoxLoginAutoStart.setText(_translate("formLogin", "Iniciar junto com o Windows"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("formLogin", "Login"))
        self.label_4.setText(_translate("formLogin", "Email:"))
        self.label_6.setText(_translate("formLogin", "Senha atual:"))
        self.label_5.setText(_translate("formLogin", "Repetir nova senha:"))
        self.label_7.setText(_translate("formLogin", "Nova senha:"))
        self.btnAlterarSenha.setText(_translate("formLogin", "Alterar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("formLogin", "Alterar Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formLogin = QtWidgets.QWidget()
    ui = Ui_formLogin()
    ui.setupUi(formLogin)
    formLogin.show()
    sys.exit(app.exec_())
