# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formInitGui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_formInitGui(object):
    def setupUi(self, formInitGui):
        formInitGui.setObjectName("formInitGui")
        formInitGui.setWindowModality(QtCore.Qt.WindowModal)
        formInitGui.resize(1103, 801)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(formInitGui.sizePolicy().hasHeightForWidth())
        formInitGui.setSizePolicy(sizePolicy)
        formInitGui.setAcceptDrops(True)
        self.gridLayoutWidget = QtWidgets.QWidget(formInitGui)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 1101, 701))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridCam = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridCam.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridCam.setContentsMargins(0, 0, 0, 0)
        self.gridCam.setObjectName("gridCam")
        self.lblCam1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCam1.sizePolicy().hasHeightForWidth())
        self.lblCam1.setSizePolicy(sizePolicy)
        self.lblCam1.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCam1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCam1.setMidLineWidth(0)
        self.lblCam1.setText("")
        self.lblCam1.setObjectName("lblCam1")
        self.gridCam.addWidget(self.lblCam1, 0, 0, 1, 1)
        self.lblCam3 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCam3.sizePolicy().hasHeightForWidth())
        self.lblCam3.setSizePolicy(sizePolicy)
        self.lblCam3.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCam3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCam3.setText("")
        self.lblCam3.setObjectName("lblCam3")
        self.gridCam.addWidget(self.lblCam3, 1, 0, 1, 1)
        self.lblCam4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCam4.sizePolicy().hasHeightForWidth())
        self.lblCam4.setSizePolicy(sizePolicy)
        self.lblCam4.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCam4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCam4.setText("")
        self.lblCam4.setObjectName("lblCam4")
        self.gridCam.addWidget(self.lblCam4, 1, 1, 1, 1)
        self.lblCam2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblCam2.sizePolicy().hasHeightForWidth())
        self.lblCam2.setSizePolicy(sizePolicy)
        self.lblCam2.setFrameShape(QtWidgets.QFrame.Box)
        self.lblCam2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lblCam2.setText("")
        self.lblCam2.setObjectName("lblCam2")
        self.gridCam.addWidget(self.lblCam2, 0, 1, 1, 1)
        self.btnInitAddRegiao = QtWidgets.QPushButton(formInitGui)
        self.btnInitAddRegiao.setGeometry(QtCore.QRect(3, 5, 111, 41))
        self.btnInitAddRegiao.setObjectName("btnInitAddRegiao")
        self.btnInitSair = QtWidgets.QPushButton(formInitGui)
        self.btnInitSair.setGeometry(QtCore.QRect(990, 4, 111, 41))
        self.btnInitSair.setObjectName("btnInitSair")
        self.btnInitConfig = QtWidgets.QPushButton(formInitGui)
        self.btnInitConfig.setGeometry(QtCore.QRect(120, 5, 111, 41))
        self.btnInitConfig.setObjectName("btnInitConfig")
        self.horizontalLayoutWidget = QtWidgets.QWidget(formInitGui)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 760, 1101, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(150, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.retranslateUi(formInitGui)
        QtCore.QMetaObject.connectSlotsByName(formInitGui)

    def retranslateUi(self, formInitGui):
        _translate = QtCore.QCoreApplication.translate
        formInitGui.setWindowTitle(_translate("formInitGui", "Portão Virtual"))
        self.btnInitAddRegiao.setText(_translate("formInitGui", "+ Região"))
        self.btnInitSair.setText(_translate("formInitGui", "Sair"))
        self.btnInitConfig.setText(_translate("formInitGui", "Configurações"))
        self.label.setText(_translate("formInitGui", "Versão 1.0"))
        self.label_2.setText(_translate("formInitGui", "Status:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formInitGui = QtWidgets.QWidget()
    ui = Ui_formInitGui()
    ui.setupUi(formInitGui)
    formInitGui.show()
    sys.exit(app.exec_())

