# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formConfig(object):
    def setupUi(self, formConfig):
        formConfig.setObjectName("formConfig")
        formConfig.setWindowModality(QtCore.Qt.WindowModal)
        formConfig.resize(933, 685)
        formConfig.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabConfig = QtWidgets.QTabWidget(formConfig)
        self.tabConfig.setGeometry(QtCore.QRect(20, 10, 911, 671))
        self.tabConfig.setTabsClosable(True)
        self.tabConfig.setObjectName("tabConfig")
        self.tabRegion = QtWidgets.QWidget()
        self.tabRegion.setObjectName("tabRegion")
        self.formLayoutWidget = QtWidgets.QWidget(self.tabRegion)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 60, 265, 197))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formRegion = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formRegion.setContentsMargins(0, 0, 0, 0)
        self.formRegion.setObjectName("formRegion")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formRegion.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txtRegionName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txtRegionName.setObjectName("txtRegionName")
        self.formRegion.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtRegionName)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formRegion.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.checkDog = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkDog.setTristate(False)
        self.checkDog.setObjectName("checkDog")
        self.formRegion.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkDog)
        self.checkBike = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkBike.setTristate(False)
        self.checkBike.setObjectName("checkBike")
        self.formRegion.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBike)
        self.checkCar = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkCar.setTristate(False)
        self.checkCar.setObjectName("checkCar")
        self.formRegion.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.checkCar)
        self.checkPerson = QtWidgets.QCheckBox(self.formLayoutWidget)
        self.checkPerson.setTristate(False)
        self.checkPerson.setObjectName("checkPerson")
        self.formRegion.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkPerson)
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tabRegion)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 280, 160, 41))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formAccuracy = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formAccuracy.setContentsMargins(0, 0, 0, 0)
        self.formAccuracy.setObjectName("formAccuracy")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.formAccuracy.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.txtThreshold = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.txtThreshold.setText("")
        self.txtThreshold.setPlaceholderText("")
        self.txtThreshold.setObjectName("txtThreshold")
        self.formAccuracy.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtThreshold)
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tabRegion)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(460, 60, 411, 336))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formAlarm = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formAlarm.setContentsMargins(0, 0, 0, 0)
        self.formAlarm.setObjectName("formAlarm")
        self.formTime = QtWidgets.QFormLayout()
        self.formTime.setObjectName("formTime")
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.formTime.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.txtNameAlarm = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.txtNameAlarm.setObjectName("txtNameAlarm")
        self.formTime.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.txtNameAlarm)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_3.setObjectName("label_3")
        self.formTime.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.checkMon = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkMon.setTristate(False)
        self.checkMon.setObjectName("checkMon")
        self.formTime.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.checkMon)
        self.checkFri = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkFri.setTristate(False)
        self.checkFri.setObjectName("checkFri")
        self.formTime.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkFri)
        self.checkTue = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkTue.setTristate(False)
        self.checkTue.setObjectName("checkTue")
        self.formTime.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.checkTue)
        self.checkSat = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkSat.setTristate(False)
        self.checkSat.setObjectName("checkSat")
        self.formTime.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.checkSat)
        self.checkWed = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkWed.setTristate(False)
        self.checkWed.setObjectName("checkWed")
        self.formTime.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkWed)
        self.checkSun = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkSun.setObjectName("checkSun")
        self.formTime.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.checkSun)
        self.checkThur = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkThur.setTristate(False)
        self.checkThur.setObjectName("checkThur")
        self.formTime.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.checkThur)
        self.formAlarm.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formTime)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.formAlarm.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.formAlarm.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.timeStart = QtWidgets.QTimeEdit(self.formLayoutWidget_3)
        self.timeStart.setObjectName("timeStart")
        self.formAlarm.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.timeStart)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.formAlarm.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.timeEnd = QtWidgets.QTimeEdit(self.formLayoutWidget_3)
        self.timeEnd.setObjectName("timeEnd")
        self.formAlarm.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeEnd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSaveAlarm = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnSaveAlarm.setEnabled(True)
        self.btnSaveAlarm.setObjectName("btnSaveAlarm")
        self.horizontalLayout.addWidget(self.btnSaveAlarm)
        self.btnDeleteAlarm = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnDeleteAlarm.setObjectName("btnDeleteAlarm")
        self.horizontalLayout.addWidget(self.btnDeleteAlarm)
        self.btnCancelAlarm = QtWidgets.QPushButton(self.formLayoutWidget_3)
        self.btnCancelAlarm.setObjectName("btnCancelAlarm")
        self.horizontalLayout.addWidget(self.btnCancelAlarm)
        self.formAlarm.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.checkEmailAlert = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkEmailAlert.setCheckable(True)
        self.checkEmailAlert.setChecked(False)
        self.checkEmailAlert.setTristate(False)
        self.checkEmailAlert.setObjectName("checkEmailAlert")
        self.formAlarm.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.checkEmailAlert)
        self.checkAlertSound = QtWidgets.QCheckBox(self.formLayoutWidget_3)
        self.checkAlertSound.setObjectName("checkAlertSound")
        self.formAlarm.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.checkAlertSound)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tabRegion)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 441, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.comboRegions = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboRegions.sizePolicy().hasHeightForWidth())
        self.comboRegions.setSizePolicy(sizePolicy)
        self.comboRegions.setObjectName("comboRegions")
        self.horizontalLayout_2.addWidget(self.comboRegions)
        self.btnNewRegion = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnNewRegion.setObjectName("btnNewRegion")
        self.horizontalLayout_2.addWidget(self.btnNewRegion)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabRegion)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(460, 10, 391, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.comboAlarms = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.comboAlarms.setMinimumSize(QtCore.QSize(200, 0))
        self.comboAlarms.setCurrentText("")
        self.comboAlarms.setObjectName("comboAlarms")
        self.horizontalLayout_3.addWidget(self.comboAlarms)
        self.btnNewAlarm = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btnNewAlarm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnNewAlarm.setObjectName("btnNewAlarm")
        self.horizontalLayout_3.addWidget(self.btnNewAlarm)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tabRegion)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 399, 391, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnSaveRegion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSaveRegion.setObjectName("btnSaveRegion")
        self.horizontalLayout_4.addWidget(self.btnSaveRegion)
        self.btnDeleteRegion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnDeleteRegion.setObjectName("btnDeleteRegion")
        self.horizontalLayout_4.addWidget(self.btnDeleteRegion)
        self.btnCancelRegion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnCancelRegion.setObjectName("btnCancelRegion")
        self.horizontalLayout_4.addWidget(self.btnCancelRegion)
        self.tabConfig.addTab(self.tabRegion, "")
        self.tabConfigGeneral = QtWidgets.QWidget()
        self.tabConfigGeneral.setObjectName("tabConfigGeneral")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabConfigGeneral)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(2, 30, 791, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBoxVideoRecordingOnAlarmes = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxVideoRecordingOnAlarmes.setObjectName("checkBoxVideoRecordingOnAlarmes")
        self.gridLayout.addWidget(self.checkBoxVideoRecordingOnAlarmes, 2, 0, 1, 1)
        self.txtEmailTo = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailTo.setObjectName("txtEmailTo")
        self.gridLayout.addWidget(self.txtEmailTo, 14, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 9, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.txtEmailSubject = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailSubject.setObjectName("txtEmailSubject")
        self.gridLayout.addWidget(self.txtEmailSubject, 13, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 1, 0, 1, 1)
        self.checkBoxVideoRecordingAllTime = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxVideoRecordingAllTime.setObjectName("checkBoxVideoRecordingAllTime")
        self.gridLayout.addWidget(self.checkBoxVideoRecordingAllTime, 0, 0, 1, 1)
        self.txtDirRecordingAllTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDirRecordingAllTime.setObjectName("txtDirRecordingAllTime")
        self.gridLayout.addWidget(self.txtDirRecordingAllTime, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 7, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 10, 0, 1, 1)
        self.txtEmailSmtp = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailSmtp.setObjectName("txtEmailSmtp")
        self.gridLayout.addWidget(self.txtEmailSmtp, 10, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 12, 0, 1, 1)
        self.txtEmailUser = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailUser.setObjectName("txtEmailUser")
        self.gridLayout.addWidget(self.txtEmailUser, 11, 1, 1, 1)
        self.txtEmailPort = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailPort.setObjectName("txtEmailPort")
        self.gridLayout.addWidget(self.txtEmailPort, 9, 1, 1, 1)
        self.checkBoxWebCam = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBoxWebCam.setObjectName("checkBoxWebCam")
        self.gridLayout.addWidget(self.checkBoxWebCam, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 13, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 14, 0, 1, 1)
        self.txtEmailPassword = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailPassword.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.txtEmailPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtEmailPassword.setObjectName("txtEmailPassword")
        self.gridLayout.addWidget(self.txtEmailPassword, 12, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 11, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 6, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 8, 0, 1, 1)
        self.txtEmailName = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEmailName.setObjectName("txtEmailName")
        self.gridLayout.addWidget(self.txtEmailName, 8, 1, 1, 1)
        self.txtUrlRstp = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtUrlRstp.setObjectName("txtUrlRstp")
        self.gridLayout.addWidget(self.txtUrlRstp, 5, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 1)
        self.txtDirRecordingOnAlarmes = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtDirRecordingOnAlarmes.setObjectName("txtDirRecordingOnAlarmes")
        self.gridLayout.addWidget(self.txtDirRecordingOnAlarmes, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tabConfigGeneral)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 187, 16))
        self.label_12.setObjectName("label_12")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tabConfigGeneral)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 590, 791, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnSaveEmail = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.btnSaveEmail.setObjectName("btnSaveEmail")
        self.horizontalLayout_5.addWidget(self.btnSaveEmail)
        self.tabConfig.addTab(self.tabConfigGeneral, "")
        self.tabStorage = QtWidgets.QWidget()
        self.tabStorage.setObjectName("tabStorage")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabStorage)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 701, 325))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 15, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_26)
        self.radioButtonDeleteOldestFiles = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButtonDeleteOldestFiles.setObjectName("radioButtonDeleteOldestFiles")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.radioButtonDeleteOldestFiles)
        self.radioButtonStopSaveNewVideos = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.radioButtonStopSaveNewVideos.setObjectName("radioButtonStopSaveNewVideos")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.radioButtonStopSaveNewVideos)
        self.gridLayout_2.addLayout(self.formLayout, 19, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 14, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 10, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 7, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 0, 0, 1, 1)
        self.txtDefinirMaximoAllTime = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDefinirMaximoAllTime.sizePolicy().hasHeightForWidth())
        self.txtDefinirMaximoAllTime.setSizePolicy(sizePolicy)
        self.txtDefinirMaximoAllTime.setObjectName("txtDefinirMaximoAllTime")
        self.gridLayout_2.addWidget(self.txtDefinirMaximoAllTime, 11, 1, 1, 1)
        self.checkBoxNoLimitsVideosAllTime = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxNoLimitsVideosAllTime.setObjectName("checkBoxNoLimitsVideosAllTime")
        self.gridLayout_2.addWidget(self.checkBoxNoLimitsVideosAllTime, 11, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 11, 0, 1, 1)
        self.progressBarDisponivelHD = QtWidgets.QProgressBar(self.gridLayoutWidget_2)
        self.progressBarDisponivelHD.setProperty("value", 24)
        self.progressBarDisponivelHD.setObjectName("progressBarDisponivelHD")
        self.gridLayout_2.addWidget(self.progressBarDisponivelHD, 0, 1, 1, 1)
        self.txtDiasEstimado = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtDiasEstimado.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDiasEstimado.sizePolicy().hasHeightForWidth())
        self.txtDiasEstimado.setSizePolicy(sizePolicy)
        self.txtDiasEstimado.setObjectName("txtDiasEstimado")
        self.gridLayout_2.addWidget(self.txtDiasEstimado, 10, 1, 1, 1)
        self.txtDefinirMaximoOnAlarmes = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDefinirMaximoOnAlarmes.sizePolicy().hasHeightForWidth())
        self.txtDefinirMaximoOnAlarmes.setSizePolicy(sizePolicy)
        self.txtDefinirMaximoOnAlarmes.setObjectName("txtDefinirMaximoOnAlarmes")
        self.gridLayout_2.addWidget(self.txtDefinirMaximoOnAlarmes, 14, 1, 1, 1)
        self.txtAvisoUtilizacaoHD = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAvisoUtilizacaoHD.sizePolicy().hasHeightForWidth())
        self.txtAvisoUtilizacaoHD.setSizePolicy(sizePolicy)
        self.txtAvisoUtilizacaoHD.setObjectName("txtAvisoUtilizacaoHD")
        self.gridLayout_2.addWidget(self.txtAvisoUtilizacaoHD, 15, 1, 1, 1)
        self.checkBoxNoLimitsVideosOnAlarmes = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        self.checkBoxNoLimitsVideosOnAlarmes.setObjectName("checkBoxNoLimitsVideosOnAlarmes")
        self.gridLayout_2.addWidget(self.checkBoxNoLimitsVideosOnAlarmes, 14, 2, 1, 1)
        self.txtDirUsedVideosAllTime = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtDirUsedVideosAllTime.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDirUsedVideosAllTime.sizePolicy().hasHeightForWidth())
        self.txtDirUsedVideosAllTime.setSizePolicy(sizePolicy)
        self.txtDirUsedVideosAllTime.setObjectName("txtDirUsedVideosAllTime")
        self.gridLayout_2.addWidget(self.txtDirUsedVideosAllTime, 1, 1, 1, 1)
        self.txtDirUsedVideosOnAlarmes = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtDirUsedVideosOnAlarmes.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDirUsedVideosOnAlarmes.sizePolicy().hasHeightForWidth())
        self.txtDirUsedVideosOnAlarmes.setSizePolicy(sizePolicy)
        self.txtDirUsedVideosOnAlarmes.setObjectName("txtDirUsedVideosOnAlarmes")
        self.gridLayout_2.addWidget(self.txtDirUsedVideosOnAlarmes, 7, 1, 1, 1)
        self.txtAvailableHD = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtAvailableHD.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtAvailableHD.sizePolicy().hasHeightForWidth())
        self.txtAvailableHD.setSizePolicy(sizePolicy)
        self.txtAvailableHD.setObjectName("txtAvailableHD")
        self.gridLayout_2.addWidget(self.txtAvailableHD, 0, 2, 1, 1)
        self.btnSaveStorage = QtWidgets.QPushButton(self.tabStorage)
        self.btnSaveStorage.setGeometry(QtCore.QRect(220, 340, 89, 25))
        self.btnSaveStorage.setObjectName("btnSaveStorage")
        self.btnResetarPadraoArmazenamento = QtWidgets.QPushButton(self.tabStorage)
        self.btnResetarPadraoArmazenamento.setGeometry(QtCore.QRect(320, 340, 131, 25))
        self.btnResetarPadraoArmazenamento.setObjectName("btnResetarPadraoArmazenamento")
        self.tabConfig.addTab(self.tabStorage, "")

        self.retranslateUi(formConfig)
        self.tabConfig.setCurrentIndex(2)
        self.comboAlarms.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(formConfig)
        formConfig.setTabOrder(self.tabConfig, self.comboRegions)
        formConfig.setTabOrder(self.comboRegions, self.btnNewRegion)
        formConfig.setTabOrder(self.btnNewRegion, self.txtRegionName)
        formConfig.setTabOrder(self.txtRegionName, self.checkPerson)
        formConfig.setTabOrder(self.checkPerson, self.checkCar)
        formConfig.setTabOrder(self.checkCar, self.checkBike)
        formConfig.setTabOrder(self.checkBike, self.checkDog)
        formConfig.setTabOrder(self.checkDog, self.txtThreshold)
        formConfig.setTabOrder(self.txtThreshold, self.comboAlarms)
        formConfig.setTabOrder(self.comboAlarms, self.btnNewAlarm)
        formConfig.setTabOrder(self.btnNewAlarm, self.txtNameAlarm)
        formConfig.setTabOrder(self.txtNameAlarm, self.checkMon)
        formConfig.setTabOrder(self.checkMon, self.checkTue)
        formConfig.setTabOrder(self.checkTue, self.checkWed)
        formConfig.setTabOrder(self.checkWed, self.checkThur)
        formConfig.setTabOrder(self.checkThur, self.checkEmailAlert)
        formConfig.setTabOrder(self.checkEmailAlert, self.checkFri)
        formConfig.setTabOrder(self.checkFri, self.checkSat)
        formConfig.setTabOrder(self.checkSat, self.checkSun)
        formConfig.setTabOrder(self.checkSun, self.checkAlertSound)
        formConfig.setTabOrder(self.checkAlertSound, self.timeStart)
        formConfig.setTabOrder(self.timeStart, self.timeEnd)
        formConfig.setTabOrder(self.timeEnd, self.btnSaveAlarm)
        formConfig.setTabOrder(self.btnSaveAlarm, self.btnDeleteAlarm)
        formConfig.setTabOrder(self.btnDeleteAlarm, self.btnCancelAlarm)
        formConfig.setTabOrder(self.btnCancelAlarm, self.btnSaveRegion)
        formConfig.setTabOrder(self.btnSaveRegion, self.btnDeleteRegion)
        formConfig.setTabOrder(self.btnDeleteRegion, self.btnCancelRegion)
        formConfig.setTabOrder(self.btnCancelRegion, self.checkBoxVideoRecordingAllTime)
        formConfig.setTabOrder(self.checkBoxVideoRecordingAllTime, self.txtDirRecordingAllTime)
        formConfig.setTabOrder(self.txtDirRecordingAllTime, self.checkBoxWebCam)
        formConfig.setTabOrder(self.checkBoxWebCam, self.txtUrlRstp)
        formConfig.setTabOrder(self.txtUrlRstp, self.txtEmailName)
        formConfig.setTabOrder(self.txtEmailName, self.txtEmailPort)
        formConfig.setTabOrder(self.txtEmailPort, self.txtEmailSmtp)
        formConfig.setTabOrder(self.txtEmailSmtp, self.txtEmailUser)
        formConfig.setTabOrder(self.txtEmailUser, self.txtEmailPassword)
        formConfig.setTabOrder(self.txtEmailPassword, self.txtEmailSubject)
        formConfig.setTabOrder(self.txtEmailSubject, self.txtEmailTo)
        formConfig.setTabOrder(self.txtEmailTo, self.btnSaveEmail)

    def retranslateUi(self, formConfig):
        _translate = QtCore.QCoreApplication.translate
        formConfig.setWindowTitle(_translate("formConfig", "Configurações"))
        self.label.setText(_translate("formConfig", "Nome:"))
        self.label_2.setText(_translate("formConfig", "Tipo de reconhecimento"))
        self.checkDog.setText(_translate("formConfig", "Cachorro"))
        self.checkBike.setText(_translate("formConfig", "Moto"))
        self.checkCar.setText(_translate("formConfig", "Carro"))
        self.checkPerson.setText(_translate("formConfig", "Pessoa"))
        self.label_11.setText(_translate("formConfig", "Acurácia (%)"))
        self.label_9.setText(_translate("formConfig", "Nome:"))
        self.label_3.setText(_translate("formConfig", "Dias"))
        self.checkMon.setText(_translate("formConfig", "Seg"))
        self.checkFri.setText(_translate("formConfig", "Sex"))
        self.checkTue.setText(_translate("formConfig", "Ter"))
        self.checkSat.setText(_translate("formConfig", "Sab"))
        self.checkWed.setText(_translate("formConfig", "Qua"))
        self.checkSun.setText(_translate("formConfig", "Dom"))
        self.checkThur.setText(_translate("formConfig", "Qui"))
        self.label_4.setText(_translate("formConfig", "Horários"))
        self.label_5.setText(_translate("formConfig", "Início"))
        self.label_6.setText(_translate("formConfig", "Fim"))
        self.btnSaveAlarm.setText(_translate("formConfig", "Salvar"))
        self.btnDeleteAlarm.setText(_translate("formConfig", "Deletar"))
        self.btnCancelAlarm.setText(_translate("formConfig", "Cancelar"))
        self.checkEmailAlert.setText(_translate("formConfig", "Alerta de Email"))
        self.checkAlertSound.setText(_translate("formConfig", "Alerta Sonoro"))
        self.label_7.setText(_translate("formConfig", "Regiões:"))
        self.btnNewRegion.setText(_translate("formConfig", "+ Nova região"))
        self.label_8.setText(_translate("formConfig", "Alarmes"))
        self.btnNewAlarm.setText(_translate("formConfig", "+ Novo Alarme"))
        self.btnSaveRegion.setText(_translate("formConfig", "Salvar Região"))
        self.btnDeleteRegion.setText(_translate("formConfig", "Deletar"))
        self.btnCancelRegion.setText(_translate("formConfig", "Cancelar"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.tabRegion), _translate("formConfig", "Adicionar Região"))
        self.checkBoxVideoRecordingOnAlarmes.setText(_translate("formConfig", "Gravar video - somente quando houver alarme"))
        self.txtEmailTo.setToolTip(_translate("formConfig", "<html><head/><body><p>Utilizar vírgula para separar vários destinatários</p></body></html>"))
        self.label_16.setText(_translate("formConfig", "Porta:"))
        self.label_15.setText(_translate("formConfig", "Configuração de Email"))
        self.label_14.setText(_translate("formConfig", "URL Câmera RSTP:"))
        self.label_13.setText(_translate("formConfig", "Diretório de gravação 24h:"))
        self.checkBoxVideoRecordingAllTime.setText(_translate("formConfig", "Gravar video 24h"))
        self.label_17.setText(_translate("formConfig", "SMTP:"))
        self.label_19.setText(_translate("formConfig", "Senha:"))
        self.checkBoxWebCam.setText(_translate("formConfig", "Capturar da WebCam"))
        self.label_20.setText(_translate("formConfig", "Campo \"Assunto\":"))
        self.label_21.setText(_translate("formConfig", "Destinatário(s):"))
        self.label_18.setText(_translate("formConfig", "Usuário:"))
        self.label_29.setText(_translate("formConfig", "Nome:"))
        self.txtUrlRstp.setStatusTip(_translate("formConfig", " rtsp://<IP>:<Porta>/user=<usuario>_password=<senha>_channel=<canal>_stream=0.sdp?real_stream"))
        self.txtUrlRstp.setPlaceholderText(_translate("formConfig", " rtsp://<IP>:<Porta>/user=<usuario>_password=<senha>_channel=<canal>_stream=0.sdp?real_stream"))
        self.label_22.setText(_translate("formConfig", "Diretório de gravação (Alarmes) :"))
        self.label_12.setText(_translate("formConfig", "Configurações Gerais"))
        self.btnSaveEmail.setText(_translate("formConfig", "Salvar"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.tabConfigGeneral), _translate("formConfig", "Configuração Geral"))
        self.label_27.setText(_translate("formConfig", "Aviso por email de utilização do HD (em porcentagem %):"))
        self.label_26.setText(_translate("formConfig", "O que fazer se o HD ficar cheio ?"))
        self.radioButtonDeleteOldestFiles.setText(_translate("formConfig", "Apagar videos mais antigos at&é liberar espaço"))
        self.radioButtonStopSaveNewVideos.setText(_translate("formConfig", "Não gravar videos novos"))
        self.label_30.setText(_translate("formConfig", "Definir espaço máximo de GB na pasta \"Videos Alarmes\": "))
        self.label_25.setText(_translate("formConfig", "Espaço utilizado pela pasta \"Videos 24hs\" em GB:"))
        self.label_32.setText(_translate("formConfig", "Número de dias estimado para gravação:"))
        self.label_31.setText(_translate("formConfig", "Espaço utilizado pela pasta \"Video Alarmes\" em GB:"))
        self.label_24.setText(_translate("formConfig", "Espaço disponível no HD :"))
        self.checkBoxNoLimitsVideosAllTime.setText(_translate("formConfig", "Até o disco encher"))
        self.label_28.setText(_translate("formConfig", "Definir espaço máximo de GB na pasta Videos 24 hs:"))
        self.checkBoxNoLimitsVideosOnAlarmes.setText(_translate("formConfig", "Até o disco encher"))
        self.btnSaveStorage.setText(_translate("formConfig", "Salvar"))
        self.btnResetarPadraoArmazenamento.setText(_translate("formConfig", "Resetar padrão"))
        self.tabConfig.setTabText(self.tabConfig.indexOf(self.tabStorage), _translate("formConfig", "Armazenamento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    formConfig = QtWidgets.QWidget()
    ui = Ui_formConfig()
    ui.setupUi(formConfig)
    formConfig.show()
    sys.exit(app.exec_())
